#ifndef TARGET_CFG_H
#define TARGET_CFG_H

#define FBL_FLASH_BASE_ADDR  0x60000000
#define FBL_APP_START_ADDR   0x60010000
#define FBL_APP_END_ADDR     0x7EFFFFFF

#define FBL_APP_IVT_OFFS     (0x000)
#define FBL_APP_SWINFO_OFFS  (0x200)
#define FBL_APP_ENTRY_OFFS   (0x404)

#define FBL_APP_IVT_ADDR     (FBL_APP_START_ADDR + FBL_APP_IVT_OFFS)
#define FBL_APP_ENTRY_ADDR   (FBL_APP_START_ADDR + FBL_APP_ENTRY_OFFS)
#define FBL_APP_SWINFO_ADDR  (FBL_APP_START_ADDR + FBL_APP_SWINFO_OFFS)

#define FBL_APP_ENTRY_WORD   0x00000001

#endif /* TARGET_CFG_H */

